import { expect, it } from "vitest";
import worker from "../src/worker";

it("serves a nonce-protected calculator bridge with a frame-only Desmos CSP", async () => {
  const response = await worker.fetch(new Request("https://whitebook.test/app/calculator-frame"), {
    DB: { async prepare() { throw new Error("The public calculator bridge must not query D1"); } },
    ASSETS: { async fetch() { throw new Error("The calculator bridge is generated by the Worker"); } },
    STAGING_ACCESS_CODE: "unused",
  } as never);

  expect(response.status).toBe(200);
  expect(response.headers.get("content-type")).toContain("text/html");
  const policy = response.headers.get("content-security-policy") ?? "";
  const html = await response.text();
  const nonce = /script-src 'nonce-([a-f0-9]+)'/.exec(policy)?.[1];
  expect(nonce).toBeTruthy();
  expect(policy).toContain("https://www.desmos.com");
  expect(policy).toContain("frame-ancestors 'self'");
  expect(html).toContain(`<script nonce="${nonce}">`);
  expect(html).toContain("Desmos.GraphingCalculator");
  expect(response.headers.get("cache-control")).toBe("private, no-store");
});
